services:
  typesense_upsert:
    container_name: typesense_upsert
    build: .
    volumes:
      - .:/app
    ports:
      - 5555:8000 
    env_file:
      - .env
    networks:
      global-net:

networks:
  global-net:
    external: true
